<?
 /**
 * @desc The index action
 *
 * @author Majisti
 */

$lorem = new \Majisti\Util\Model\LoremIpsumGenerator();

$content = pq('<div />')
    ->append(pq('<a />')
        ->attr('href', $this->url(array('controller' => 'auth')))
        ->html("Auth")
    )
    ->append('&nbsp;')
    ->append(pq('<a />')
        ->attr('href', $this->url(array('action' => 'reset')))
        ->html("Reset")
    )
    ->append(pq('<br />'))

    /* editors */
    ->append($this->editing('content1'))
    ->append($this->editing('content2', 'basic'))
    ->append($this->editing('content3', 'basic', $lorem->getContent(30)))
;

$this->setRenderReturn($content);
